zio.metrics.prometheus {
  host = "localhost"
  port = ${HTTP_PORT}
  endpoint = "/metrics"
}
db {
    host = ${DB_HOST}
    port = ${DB_PORT}
    name = ${DB_NAME}
    user = ${DB_USER}
    password = ${DB_PASSWORD}
    migration-enable = true
}
jwt {
    secret = ${JWT_SECRET}
    issuer = ${JWT_ISSUER}
    ttl = ${JWT_TTL}
}
auth {
    auth-token = ${AUTH_TOKEN}
}
validation {
    phone = """^(\+7|8)\d{10}$"""
    email = """^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"""
    password = """^(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>/?]).{8,}$"""
}
