db {
    users {
      host = ${DB_HOST}
      port = ${DB_PORT}
      name = ${DB_NAME}
      user = ${DB_USER}
      password = ${DB_PASSWORD}
    }
    todo_items {
      host = ${DB_HOST}
      port = ${DB_PORT}
      name = ${DB_NAME}
      user = ${DB_USER}
      password = ${DB_PASSWORD}
    }
}